apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: contest-service
  name: contest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: contest-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: contest-service
    spec:
      containers:
        - args:
            - node
            - dist/index.js
          env:
            - name: NODE_ENV
              value: production
          image: pavelmernov/contest-service
          imagePullPolicy: Never
          name: contest-service
          ports:
            - containerPort: 3002
              protocol: TCP
      restartPolicy: Always
