
apiVersion: apps/v1
kind: Deployment
metadata:
  name: contest-db
  labels:
    app: contest-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contest-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: contest-db
    spec:
      containers:
        - name: contest-db
          image: postgres:18
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: contest_database
            - name: POSTGRES_USER
              value: pavel_mernov
            - name: POSTGRES_PASSWORD
              value: "0867"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - pavel_mernov
                - -d
                - contest_database
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: contest-db-pvc
