apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: contest-service
  name: contest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: contest-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: contest-service
    spec:
      containers:
        - args:
            - node
            - dist/main.js
          env:
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: NODE_ENV
              value: production
            - name: DB_HOST
              value: contest-db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: contest_database
            - name: DB_USER
              value: pavel_mernov
            - name: DB_PASSWORD
              value: "0867"
          image: pavelmernov/contest-service
          imagePullPolicy: Never
          name: contest-service
          ports:
            - containerPort: 3002
              protocol: TCP
      restartPolicy: Always
