apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: submission-service
  name: submission-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: submission-service
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: submission-service
    spec:
      containers:
        - args:
            - node
            - dist/index.js
          env:
            - name: NODE_ENV
              value: production
            - name: DB_HOST
              value: submission-db
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: submission_database
            - name: DB_USER
              value: pavel_mernov
            - name: DB_PASSWORD
              value: "0867"
          image: pavelmernov/submission-service
          name: submission-service
          ports:
            - containerPort: 3004
              protocol: TCP
      restartPolicy: Always
