apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
    kompose.version: 1.37.0 (fb0539e64)
  labels:
    io.kompose.service: submission-db
  name: submission-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: submission-db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.yml -o k8s/
        kompose.version: 1.37.0 (fb0539e64)
      labels:
        io.kompose.service: submission-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: submission_database
            - name: POSTGRES_PASSWORD
              value: "867"
            - name: POSTGRES_USER
              value: pavel_mernov
          image: postgres:18
          livenessProbe:
            exec:
              command:
                - pg_isready -U pavel_mernov -d submission_database
            failureThreshold: 5
            periodSeconds: 5
            timeoutSeconds: 5
          name: submission-db
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: submission-volumes
      restartPolicy: Always
      volumes:
        - name: submission-volumes
          persistentVolumeClaim:
            claimName: submission-volumes
