
openapi: 3.0.3
info:
  title: Auth Service / Mock Auth Service API
  version: 1.0.0
paths:
  /metrics:
    get:
      summary: Получить метрики Prometheus
      description: Возвращает метрики в формате Prometheus.
      responses:
        '200':
          description: Метрики в формате Prometheus
          content:
            text/plain; version=0.0.4; charset=utf-8:
              schema:
                type: string
                example: '# HELP http_requests_total The total number of HTTP requests.\n# TYPE http_requests_total counter\nhttp_requests_total{method="get",code="200"} 1027 1395066363000\n'

  /api/login:
    post:
      summary: Авторизация пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
              required:
                - login
                - password
      responses:
        '200':
          description: Успешный вход
        '401':
          description: Неверные данные аутентификации
  /api/refresh:
    post:
      summary: Обновление токена авторизации
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
              required:
                - refreshToken
      responses:
        '200':
          description: Успешное обновление токена
        '400':
          description: Отсутствует токен авторизации
        '401':
          description: Токен авторизации не валиден
  /api/logout:
    post:
      summary: Удаление токена обновления
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refreshToken:
                  type: string
              required:
                - refreshToken
      responses:
        '204':
          description: Успешное удаление токена
        '400':
          description: Отсутствует токен обновления
