
openapi: 3.0.3
info:
  title: Contest Service API
  version: 1.1.0

paths:
  /api/contests:
    get:
      summary: Получить список контестов
      responses:
        '200':
          description: Список контестов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contest'

    post:
      summary: Создать контест
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContestCreate'
      responses:
        '400':
          description: Ошибка в запросе
        '201':
          description: Контест создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contest'


  /api/contests/{contestId}:
    get:
      summary: Получить контест по ID
      parameters:
        - name: contestId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Данные контеста
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contest'
        '404':
          description: Контест не найден

    put:
      summary: Обновить контест по ID
      parameters:
        - name: contestId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Contest'
      responses:
        '200':
          description: Контест успешно обновлён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contest'
        '404':
          description: Контест не найден

    delete:
      summary: Удалить контест по ID
      parameters:
        - name: contestId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Контест удалён
        '404':
          description: Контест не найден


  /api/contests/{contestId}/tasks:
    get:
      summary: Получить все задачи урока
      parameters:
        - name: contestId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Список задач урока
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

    post:
      summary: Добавить задачу в урок
      parameters:
        - name: contestId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Задача создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          description: Ошибка в запросе

  /api/tasks/{taskId}:
    get:
      summary: Получить задачу по ID
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Данные задачи
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          description: Неавторизованный доступ
        '404':
          description: Задача не найдена

    put:
      summary: Обновить задачу
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Задача обновлена
        '401':
          description: Неавторизованный доступ
        '404':
          description: Задача не найдена

    delete:
      summary: Удалить задачу
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Задача удалена
        '401':
          description: Неавторизованный доступ
        '404':
          description: Задача не найдена

  /api/tasks/{taskId}/tests:
    get:
      summary: Получить тесты задачи
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Список тестов
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Test'
        '401':
          description: Неавторизованный доступ        

    post:
      summary: Добавить тест к задаче
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TestCreate'
      responses:
        '201':
          description: Тест добавлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
        '401':
          description: Неавторизованный доступ

        '400':
          description: Ошибка в запросе

  /api/tests/{idTest}:
    get:
      summary: Получить Test по id
      parameters:
        - name: idTest
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Найденный объект Test
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
        '404':
          description: Объект не найден
        '401':
          description: Неавторизованный доступ

    put:
      summary: Обновить Test по id
      parameters:
        - name: idTest
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Test'
      responses:
        '200':
          description: Обновленный объект Test
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
        '404':
          description: Объект не найден
        '401':
          description: Неавторизованный доступ

    delete:
      summary: Удалить Test по id
      parameters:
        - name: idTest
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Успешное удаление
        '404':
          description: Объект не найден
        '401':
          description: Неавторизованный доступ

components:
  schemas:
    Contest:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        deadline:
          type: string
          format: date-time
        description:
          type: string
      required: [id, title]

    ContestCreate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        deadline:
          type: string
          format: date-time
      required: [title]

    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
        contestId:
          type: string
          format: uuid
        name:
          type: string
        numberInContest:
          type: integer
        text:
          type: string
        answerType:
          type: string
          enum: [выбор, текст, код]
        timeLimitMs:
          type: integer
        memoryLimitKb:
          type: integer
        points:
          type: integer
        attempts:
          type: integer
      required: [id, contestId, name, text, answerType]

    TaskCreate:
      type: object
      properties:
        name:
          type: string
        numberInContest:
          type: integer
        text:
          type: string
        deadline:
          type: string
          format: date-time
        answerType:
          type: string
          enum: [выбор, текст, код]
        timeLimitMs:
          type: integer
        memoryLimitKb:
          type: integer
        points:
          type: integer
        attempts:
          type: integer
      required: [name, text, answerType]

    TaskUpdate:
      type: object
      properties:
        name:
          type: string
        numberInContest:
          type: integer
        text:
          type: string
        deadline:
          type: string
          format: date-time
        answerType:
          type: string
          enum: [выбор, текст, код]
        timeLimitMs:
          type: integer
        memoryLimitKb:
          type: integer
        points:
          type: integer
        attempts:
          type: integer

    Test:
      type: object
      properties:
        idTest:
          type: string
          format: uuid
        taskId:
          type: string
          format: uuid
        inputData:
          type: string
        outputData:
          type: string
      required: [idTest, taskId, inputData, outputData]

    TestCreate:
      type: object
      properties:
        inputData:
          type: string
        outputData:
          type: string
      required: [inputData, outputData]


