
name: RiscVCourse. Build and push services

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Login to GitHub Container Registry
      #  uses: docker/login-action@v3
      #  with:
      #    registry: ghcp.io
      #    username: Pavel-Mernov
      #    password: ${{ secrets.GHCP_TOKEN }}

      - name: Build and push compilation-service
        uses: docker/build-push-action@v5
        with:
          context: ./compilation_service
          file: ./compilation_service/Dockerfile
          push: false
          # tags: ghcr.io/${{ github.repository_owner }}/compilation-service:latest

      - name: Build and push Mock auth service
        uses: docker/build-push-action@v5
        with:
          context: ./mock_auth_service
          file: ./mock_auth_service/Dockerfile
          push: false
          # tags: ghcr.io/${{ github.repository_owner }}/service-b:latest

      - name: Build and push Contest service
        uses: docker/build-push-action@v5
        with:
          context: ./contest_service
          file: ./contest_service/Dockerfile
          push: false
          # tags: ghcr.io/${{ github.repository_owner }}/service-b:latest

